[package]
name = "blackboard"
version = "0.1.0"
edition = "2021"

[dependencies]
skia-safe = { path = "../rust-skia/skia-safe", features = ["vulkan"] }
eframe = "0.18"  # Upgrade to the latest version for better compatibility
gstreamer = "0.18"
gstreamer-app = "0.18"
ash = "0.34"
